"""initial migration with all tables and indexes

Revision ID: 840dc0f71a0e
Revises:
Create Date: 2025-11-20 11:31:54.752204

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "840dc0f71a0e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=255), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("tz_id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_location_coords", "locations", ["lat", "lon"], unique=False)
    op.create_index("idx_location_name_country", "locations", ["name", "country"], unique=False)
    op.create_index(op.f("ix_locations_id"), "locations", ["id"], unique=False)
    op.create_index(op.f("ix_locations_name"), "locations", ["name"], unique=False)
    op.create_table(
        "weather_conditions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("icon", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weather_conditions_code"), "weather_conditions", ["code"], unique=True)
    op.create_index(op.f("ix_weather_conditions_id"), "weather_conditions", ["id"], unique=False)
    op.create_table(
        "weather_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("condition_id", sa.Integer(), nullable=False),
        sa.Column("localtime_epoch", sa.Integer(), nullable=False),
        sa.Column("localtime", sa.String(length=50), nullable=False),
        sa.Column("last_updated_epoch", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.String(length=50), nullable=False),
        sa.Column("temp_c", sa.Float(), nullable=False),
        sa.Column("temp_f", sa.Float(), nullable=False),
        sa.Column("feelslike_c", sa.Float(), nullable=False),
        sa.Column("feelslike_f", sa.Float(), nullable=False),
        sa.Column("windchill_c", sa.Float(), nullable=False),
        sa.Column("windchill_f", sa.Float(), nullable=False),
        sa.Column("heatindex_c", sa.Float(), nullable=False),
        sa.Column("heatindex_f", sa.Float(), nullable=False),
        sa.Column("dewpoint_c", sa.Float(), nullable=False),
        sa.Column("dewpoint_f", sa.Float(), nullable=False),
        sa.Column("wind_mph", sa.Float(), nullable=False),
        sa.Column("wind_kph", sa.Float(), nullable=False),
        sa.Column("wind_degree", sa.Integer(), nullable=False),
        sa.Column("wind_dir", sa.String(length=10), nullable=False),
        sa.Column("gust_mph", sa.Float(), nullable=False),
        sa.Column("gust_kph", sa.Float(), nullable=False),
        sa.Column("pressure_mb", sa.Float(), nullable=False),
        sa.Column("pressure_in", sa.Float(), nullable=False),
        sa.Column("precip_mm", sa.Float(), nullable=False),
        sa.Column("precip_in", sa.Float(), nullable=False),
        sa.Column("humidity", sa.Integer(), nullable=False),
        sa.Column("cloud", sa.Integer(), nullable=False),
        sa.Column("vis_km", sa.Float(), nullable=False),
        sa.Column("vis_miles", sa.Float(), nullable=False),
        sa.Column("uv", sa.Float(), nullable=False),
        sa.Column("short_rad", sa.Float(), nullable=False),
        sa.Column("diff_rad", sa.Float(), nullable=False),
        sa.Column("dni", sa.Float(), nullable=False),
        sa.Column("gti", sa.Float(), nullable=False),
        sa.Column("is_day", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["condition_id"],
            ["weather_conditions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_weather_last_updated", "weather_records", ["last_updated_epoch"], unique=False
    )
    op.create_index(
        "idx_weather_location_created",
        "weather_records",
        ["location_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_weather_upsert",
        "weather_records",
        ["location_id", "condition_id", "localtime_epoch"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weather_records_created_at"), "weather_records", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_weather_records_id"), "weather_records", ["id"], unique=False)
    op.create_index(
        op.f("ix_weather_records_location_id"), "weather_records", ["location_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_records_location_id"), table_name="weather_records")
    op.drop_index(op.f("ix_weather_records_id"), table_name="weather_records")
    op.drop_index(op.f("ix_weather_records_created_at"), table_name="weather_records")
    op.drop_index("idx_weather_upsert", table_name="weather_records")
    op.drop_index("idx_weather_location_created", table_name="weather_records")
    op.drop_index("idx_weather_last_updated", table_name="weather_records")
    op.drop_table("weather_records")
    op.drop_index(op.f("ix_weather_conditions_id"), table_name="weather_conditions")
    op.drop_index(op.f("ix_weather_conditions_code"), table_name="weather_conditions")
    op.drop_table("weather_conditions")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_index(op.f("ix_locations_id"), table_name="locations")
    op.drop_index("idx_location_name_country", table_name="locations")
    op.drop_index("idx_location_coords", table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
