FROM python:3.11-slim

WORKDIR /app

# Install uv
RUN pip install uv

# Copy the producer application into the container
COPY producer /app/producer

COPY producer/pyproject.toml producer/uv.lock ./

# Run the application
CMD ["uv", "run", "-m", "producer.producer_app.api_fetcher"]
